Dataset:
  dataset: coco
  root: "/home/ubuntu/COCO"
  train_name: "train"
  val_name: "val"
  test_name: null
  image_size: [512, 512, 3]
  nsr: null
  augs:
    horizontal_flip:
      p: 0.5
    vertical_flip:
      p: 0
    gamma:
      p: 0.5
    sharpness:
      p: 0.3
      alpha: [0.1, 0.3]
    gaussian_blur:
      p: 0.3
    contrast:
      p: 0.5
    brightness:
      p: 0.5
    color_jitter:
      p: 0.3
    shift_scale_rotate:
      p: 0.4
    superpixels:
      p: 0
    additive_noise:
      p: 0.2
    perspective:
      p: 0
    rgb_shift:
      p: 0
      r_shift_limit: 20
      g_shift_limit: 20
      b_shift_limit: 20
    cutout:
      p: 0
      max_h_size: 10
      max_w_size: 10
    min_area: 1024
    min_visibility: 0.7

Model:
  backbone:
    name: "resnet_34"
    pretrained: True
    freeze_bn: True
  anchors:
    scales: [1, 1.2599210498948732, 1.5874010519681994]
    ratios: [0.5, 1, 2]
    sizes: [32, 64, 128, 256, 512]
    strides: [8, 16, 32, 64, 128]
    prior_mean: null
    prior_std: null
  FPN:
    pyramid_levels: [3, 4, 5, 6, 7]
    channels: 256
    upsample: "nearest"
  head:
    classification:
      num_classes: 1
      n_repeat: 4
      use_bn: False
      activation: 'relu'
      loss:
        name: "focalloss"
        params:
          alpha: 0.25
          gamma: 2.0
      bias_prior: 0.01
    regression:
      n_repeat: 4
      use_bn: False
      activation: 'relu'
      loss:
        name: "smooth_l1_loss"
        params:
          beta: 0.1
Trainer:
  logdir: "/home/ubuntu/coco_logs"
  num_epochs: 100
  batch_size:
    train: 32
    val: 32
    test: 32
  optimizer:
    name: "torch.optim.Adam"
    params:
      betas: [0.9, 0.999]
      weight_decay: 1e-6
  scheduler:
    name: "torch.optim.lr_scheduler.OneCycleLR"
    params:
      max_lr: 1e-5
      anneal_strategy: 'cos'
      pct_start: 1e-5
      div_factor: 10
      final_div_factor: 1e2
  tpus: 0
  gpus: 1
  dist_backend: 'ddp'
  workers: 8
  clip_grad_norm: 0.1
  amp: True
  amp_backend: "native"
  num_sanity_val_steps: 0
  callbacks:
    checkpoint:
      enabled: True
      save_top_k: 3
      monitor: 'COCO_eval/mAP@0.5:0.95:0.05'
      mode: 'max'
      verbose: False
    early_stopping:
      enabled: True
      monitor: 'COCO_eval/mAP@0.5:0.95:0.05'
      mode: 'max'
      patience: 5
      verbose: False
    lr_monitor:
      enabled: True
      logging_interval: null
  save_val_predictions: True
  save_test_predictions: True
